GET http://localhost:3000/v1/movies

###
GET http://localhost:3000/v1/movies/25

###
POST http://localhost:3000/v1/movies
Content-Type: application/json

{
    "title": "Asmara Cinta2",
    "director": "jju",
    "release_year": 2024,
    "is_available": true
}

###
PUT http://localhost:3000/v1/movies/2
Content-Type: application/json

{
    "title": "Si Gundul",
    "director": "Joo",
    "release_year": 2032,
    "is_available": false
}

###
DELETE http://localhost:3000/v1/movies/6
